### ISSUE TITLE
Fases da criação do protótipo

### ISSUE THREAD

**Issue by jhondutrati** [FelipeCabralz/Wallets-manager#11]
Deixem aqui os comentários das fases de atualização/desenvolvimento do protótipo

**Comment by jhondutrati** [comment]
Deixem aqui os comentários das fases de atualização/desenvolvimento do protótipo

**Comment by jhondutrati** [comment]
Conforme mostrado, efetuei a criação do menu em baixo da tela principal, adicionei o botão de inserir valores, ligação de cadastro de valores, e telas de adicionar valores a receber e a pagar. Caso desejem alguma alteração na parte já criada me informem.

**Comment by felipesbcabral** [comment]
Da minha parte realizei a criação do Calendário, todas as paginas do Dark Mode, a pagina inical com participação do @jhondutrati, também a area de configurações do aplicativo, a area de editar perfil e os botões de editar e excluir despesa, com participação do Guilherme.

**Comment by jhondutrati** [comment]
efetuado algumas alterações no bottom navigation com a ajuda do Guilherme e @FelipeCabralz, alterado tela principal junto com o @FelipeCabralz, e efetuado algumas alterações de cores nas telas de adição de valores (receber / pagar)

**Comment by isaiasZ** [comment]
Da minha parte realizei a criação das paginas de crie sua conta, editar, é excluir.

**Comment by giovannaexe** [comment]
Criado o projeto no Figma, adicionei todos os meus colegas como editores na ferramenta. Criei o background das paginas iniciais e o scroll da tela principal e menu.

**Comment by GuilhermeMFortes** [comment]
Foram feitas por mim a Splash Scree, Edit User juntamente com o @FelipeCabralz e a pagina de transações com @giovannaexe e @FelipeCabralz.
Fiz também ajustes nas telas em dark mode e na prototipagem do projeto.
