### ISSUE TITLE
Criação da página inicial

### ISSUE THREAD

**Issue by felipesbcabral** [FelipeCabralz/Wallets-manager#18]
### O que fazer?

Realizar a criação da tela inicial onde terá um bottom menu, e vários outros botões.

---

### Como fazer:

Quando o usuário realizar o login/cadastro ele deverá ser redirecionado para a tela inicial do aplicativo, onde terá um bottom menu, balanço total do dinheiro, renda, despesas, e também no canto superior esquerdo a foto do usuário que ao ser clicado será redirecionado para a página de editar perfil, e também na direita um botão onde será enviado para a área de configurações do usuário, e vários botões que enviarão o usuário para cada respectiva conta registrada. 
Neste link voce encontrará a documentação do React Native que pode te ajudar no processo de criação: **[React Native Documentação](https://reactnative.dev/)**

---
Testes/Tests
- [x] Não esquecer de fazer testes no celular e no computador para verificar se está funcionando corretamente.
- [x] Postar evidencia de que a tela está completa e está funcionando como o esperado.
---

### Exemplo de como a tela deve ser:
![image (3)](https://user-images.githubusercontent.com/78245415/164915157-ce86088b-4a84-4218-a41d-3fd1bdbacaa6.png)

**Comment by luisagnes** [comment]
estarei fazendo essa tela
