### ISSUE TITLE
Criar pagina inicial 

### ISSUE THREAD

**Issue by felipesbcabral** [FelipeCabralz/Wallets-manager#5]
https://i.pinimg.com/originals/1a/bd/cf/1abdcfb7d86e84f95d1b367e37abff1d.png Paleta de cor para testes

link para ícones https://fonts.google.com/icons
link secundario para app https://material.io/

**Comment by jhondutrati** [comment]
up

**Comment by luisagnes** [comment]
up

**Comment by GuilhermeMFortes** [comment]
Up

**Comment by jhondutrati** [comment]
link para ícones https://fonts.google.com/icons
link secundario para app https://material.io

**Comment by luisagnes** [comment]
beleza, so mandando algo aqui pra eu lembrar de salvar
