### ISSUE TITLE
Ideias de projeto

### ISSUE THREAD

**Issue by jhondutrati** [FelipeCabralz/Wallets-manager#9]
Boa noite, conforme havíamos conversado antes, tive a ideia do app de gestão financeira, no qual o mesmo terá os gastos mensais, um histórico de gastos e uma função de editar valores, caso tenham mais ideias escrevam aqui.

**Comment by felipesbcabral** [comment]
Uma ótima ideia, e nós também poderíamos fazer lembretes de pagamentos.

**Comment by jhondutrati** [comment]
> Uma ótima ideia, e nós também poderíamos fazer lembretes de pagamentos.

Ótimo

**Comment by isaiasZ** [comment]
ótima ideia @jhondutrati, o que também acrescentaria seria uma área para perfil do usuário.

**Comment by felipesbcabral** [comment]
E também seria legal um calendário de scroll para melhorar a experiencia do usuário na hora de pesquisar alguma data!

**Comment by felipesbcabral** [comment]
Também acho que seria muito interessante se o aplicativo tivesse um tema dark mode e fique a critério do usuário qual usar.

**Comment by julianodornasS05** [comment]
acho interessante que alem do modo dark, na redefinição de senha, tivesse como confirmar por celular ou pelo email, que e você mesmo que esta redefinindo a sua senha, uma maior segurança para o app
